---
- name: Configure MongoDb Server
  hosts: db
  become: yes
  roles:
    - common
    - mongodb

- name: Configure Web Server
  hosts: web
  become: yes
  roles:
    - common
    - nodejs
    - nginx
    - app
    - prometheus
    - grafana